# Generated by Django 2.2.6 on 2019-11-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name company')),
                ('address', models.CharField(max_length=50, verbose_name='address')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('education', models.CharField(max_length=50, verbose_name='education')),
                ('experience', models.CharField(max_length=50, verbose_name='experience')),
                ('summary', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Intership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name intership')),
                ('experience', models.CharField(max_length=50, verbose_name='experience')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employer', verbose_name='employer id')),
            ],
        ),
    ]
