# Generated by Django 2.2.6 on 2019-11-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191114_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intership',
            options={'verbose_name_plural': 'interships'},
        ),
    ]
