# Generated by Django 2.2.6 on 2019-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191114_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
