# Generated by Django 2.2.6 on 2019-11-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191114_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to='users/'),
        ),
    ]
