# Generated by Django 2.2.6 on 2019-11-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191114_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
