# Generated by Django 2.2.6 on 2019-11-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191114_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='summary',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
